# Generated by Django 5.2.7 on 2025-12-18 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo_park', '0002_product_order_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фикс. оклад'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка ₽/час'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Почасовая'), ('fixed', 'Фиксированная')], default='hourly', max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Всего часов')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Переработка')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад/Базовая')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='За переработку')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начислено')),
                ('ndfl_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='НДФЛ (13%)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прочие удержания')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='К выплате')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('paid', 'Выплачено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='nemo_park.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Расчётный лист',
                'verbose_name_plural': 'Расчётные листы',
                'ordering': ['-period_end', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало смены')),
                ('end_time', models.TimeField(verbose_name='Конец смены')),
                ('break_minutes', models.PositiveIntegerField(default=60, verbose_name='Перерыв (мин)')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Отработано часов')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Переработка')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='nemo_park.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Рабочие смены',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
