# Generated by Django 5.2.7 on 2025-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo_park', '0003_employee_fixed_salary_employee_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_break_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Перерыв (мин)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_end_time',
            field=models.TimeField(default='18:00', verbose_name='Конец смены'),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_start_time',
            field=models.TimeField(default='09:00', verbose_name='Начало смены'),
        ),
    ]
