# Generated by Django 5.2.7 on 2025-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo_park', '0004_employee_default_break_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='default_break_minutes',
            new_name='break_minutes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='default_end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='default_start_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fixed_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days',
            field=models.CharField(default='1,2,3,4,5', help_text='1=Пн, 2=Вт, 3=Ср, 4=Чт, 5=Пт, 6=Сб, 7=Вс', max_length=20, verbose_name='Рабочие дни'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end',
            field=models.TimeField(default='18:00', verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start',
            field=models.TimeField(default='09:00', verbose_name='Начало рабочего дня'),
        ),
    ]
