# Generated by Django 5.2.7 on 2025-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo_park', '0005_rename_default_break_minutes_employee_break_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='work_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Рабочих дней'),
        ),
        migrations.DeleteModel(
            name='WorkShift',
        ),
    ]
